Fix photo carousel when accessed from multi-photo review
falling-fruit/falling-fruit-web pull request #318
Opened 2022-12-09 08:01 UTC by Qrtn

Fixes #295

2022-12-09 12:18 UTC, ezwelty requested changes
Tested locally with both single and multi-photo reviews, on a location that also contains reviews with no photos. Everything works as expected, _except_ when clicking on a banner photo from a multi-photo review. Then the page crashes with the following:

```
TypeError: Cannot read properties of undefined (reading 'map')
Lightbox
src/components/entry/Lightbox.js:156
  153 | </ExitButton>
  154 | <Review review={reviews[index[0]]} includePreview={false} />
  155 | 
> 156 | <ThumbnailImageContainer>
      | ^  157 |   {reviewImages[index[0]].map((photo, idx) => (
  158 |     <ThumbnailImage
  159 |       small
```

2022-12-10 21:09 UTC, Qrtn commented
@ezwelty I've seen this before as well but having trouble reproducing. Could you link an entry in which the page crashes for this case?

2022-12-11 07:22 UTC, ezwelty commented
> @ezwelty I've seen this before as well but having trouble reproducing. Could you link an entry in which the page crashes for this case?

@Qrtn To reproduce using the server-side test API, navigate to https://fallingfruit.org/entry/3383, then flip to the third photo in the banner carousel (or any other photo in the multi-photo review), and click on it. Error is thrown whether logged in or not, whether review is mine or not.

2022-12-26 21:40 UTC, ezwelty approved these changes

2022-12-26 21:42 UTC, merged