fix unexpected behavior of back button in side panel settings
falling-fruit/falling-fruit-web pull request #486
Opened 2024-10-07 06:49 UTC by badaminatasha

From desktop: if settings page is opened in side panel, and user clicks on different locations on the map, the back button on the settings page goes through the location history before finally closing the settings page. Instead, it should leave the map as-is and only close the settings page. This bug was because the settings page back button used goBack function in onClick, whereas other similar components were using goToMap, which has the desired effect. Updated back button to use goToMap.

2024-10-08 00:59 UTC, badaminatasha commented
Addresses #484

2024-10-08 01:01 UTC, badaminatasha commented
Closes #484

2024-10-08 08:17 UTC, wbazant commented
@badaminatasha thanks for making the change! Always going back to map follows user intention a bit better than going back in history, but we can access the settings page from a few more places - from my memory, the user could also be viewing a location, adding a location, editing a location, or editing a review.

A more complete implementation would use the state in Redux to figure out where to go back to - for example if there's a location id go back to the page of that location. Would you be interested in having a go? We do something like this for mobile, where being in settings and clicking a "map" icon does a few different things depending on the state. See implementation at https://github.com/falling-fruit/falling-fruit-web/blob/2437ae427242bd09fb6d19ca2eeac6ec85aab4aa/src/components/mobile/Tabs.js#L71 .

2024-10-25 10:23 UTC, wbazant requested changes
Allow going back to not just the map page

2024-10-27 17:48 UTC, wbazant commented
Closed in favour of #545

2024-10-27 17:48 UTC, closed without merging